### PR TITLE
[43] language selection button

### PR DESCRIPTION
**Pull request by quadraticat**
**Resolves:** [#43](https://github.com/unraid/usb-creator-next/issues/43)

**Changes:**

- Updated GUI to have a "Select Language" button and implemented the language select functionality to it.

**Testing:**

- Built and tested feature. Screenshots included below.

image

image

**Notes:**

- Should we create an icon for it like Info and Help?
- Should the language select menu be able to be hidden when pressed again?

### CODE REVIEW

**Comment by elibosley** [comment]
- Should we create an icon for it like Info and Help?



- Should the language select menu be able to be hidden when pressed again?

**Comment by elibosley** [comment]
This is awesome! Any chance you have figured out how the translator tool works so we can get you some translations? Can you maybe try to update the XML files to match the EN_US version and pull all translation strings for we can get things translated?

**Comment by elibosley** [comment]
language
Here's the SVG - BTW these are all from HeroIcons : https://heroicons.com/ for future reference!

**Comment by elibosley** [comment]
Q on this - any chance we can get the language files out somehow or into a format that we can translate? Ideally we'd convert the english one somehow to every other language xml (specifically the ones listed in the screenshot below) and then I can send those files to our translator.

Screenshot 2024-09-30 at 12 49 41

**Comment by quadraticat** [comment]
Update:

- Created a new ts file for the English strings. All of the old rpi translations are now moved to a folder called legacy for reference. I made an almost complete Spanish translation as an example/for testing. 
- I went ahead and made it so when you press Select Language it will either show or hide the language selection bar.
- Added the language icon
- Made it so Spanish shows as Español in the language list

**Pull request merged**
